apiVersion: v1
kind: Pod
metadata:
 name: mypod
 labels:
   env: dev
spec:
   containers:
   - name: "mytask3"
     image: "vimal13/apache-webserver-php"
     volumeMounts:
     - name: myvol
       mountPath: /var/www/html
     volumes:
      - name: myvol
        persistentVolumeClaim:
           claimName: web-volume1

